### ISSUE TITLE
[BUG] nhqm crashing on nullref

### ISSUE THREAD

**Issue by jakubsuchybio** [nicehash/NiceHashQuickMiner#992]
**Describe the bug**
From the logs:
[2024-12-29 07:43:16:231] [FATAL] [Program] System.NullReferenceException: Object reference not set to an instance of an object.
   at watchdog2.watchdog.switch_devices()
   at watchdog2.watchdog.worker_thread()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**To Reproduce**
Don't have a repro, but lately when I run it over night, this just happens...

**Expected behavior**
nhqm shouldn't crash

**Version affected (please complete the following information):**
 - Version number 0.6.12.0
 - STABLE

**NVIDIA driver version**
566.36

**Hardware**
NVIDIA 3090
i9 - 9900K

**Logs**
I don't have a capacity to go through the logs if there are some secrets or not... That fatal log is from those logs

**Additional context**
Other behavior that is happening is that excavator is restarting, but there are no errors there. I just set "do nothing" when some error in excavator occurs, will monitor further

**Comment by mkchmiel** [comment]
Having same issue on latest and experimental, what sucks for me i get stuck in a crash loop
evga 3080ti
7950x3d
